### Get Random Quote (Returns single random quote or error if none)
GET http://127.0.0.1:8000/quotes/random

### Get First 3 Quotes (Returns up to 3 quotes)
GET http://127.0.0.1:8000/quotes?skip=0&limit=3


### Get Next 3 Quotes (Skips first 3, returns next set)
GET http://127.0.0.1:8000/quotes?skip=3&limit=3


### Get All Quotes Default (Defaults to 10 if no limit provided)
GET http://127.0.0.1:8000/quotes


### Get All Quotes with Large Limit (Capped at total available)
GET http://127.0.0.1:8000/quotes?skip=0&limit=100


### Get Quotes with Skip Beyond Range (Expect "No quotes found")
GET http://127.0.0.1:8000/quotes?skip=999&limit=5

### Add Valid Quote 1
POST http://127.0.0.1:8000/quotes
Content-Type: application/json

{
  "text": "Test quote from VSCode",
  "author": "VSCode Tester"
}


### Add Valid Quote 2
POST http://127.0.0.1:8000/quotes
Content-Type: application/json

{
  "text": "Discipline is freedom.",
  "author": "Anonymous"
}


### Add Invalid Quote (Empty text)
POST http://127.0.0.1:8000/quotes
Content-Type: application/json

{
  "text": "",
  "author": "Test"
}


### Add Invalid Quote (Empty author)
POST http://127.0.0.1:8000/quotes
Content-Type: application/json

{
  "text": "Great quote",
  "author": ""
}

### Delete Quote by ID
DELETE http://127.0.0.1:8000/quotes/[Insert_ID]  

### Delete All Quotes
DELETE http://127.0.0.1:8000/quotes 

### Update Existing Quote
PATCH http://127.0.0.1:8000/quotes/6865c2f971f9e01bf1a41b28
Content-Type: application/json

{
  "text": "Updated wisdom.",
  "author": "Editor"
}

### Search Quotes
GET http://127.0.0.1:8000/quotes/search?query=